# Generated by Django 3.1 on 2020-08-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyac_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employeeID',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
