# Generated by Django 3.1 on 2020-08-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyac_api', '0002_customuser_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='age_group',
            field=models.CharField(choices=[('5-9', '5-9'), ('10-17', '10-17'), ('18-26', '18-26'), ('27-35', '27-35')], default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='image',
            field=models.ImageField(default=3, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='name',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
