# Generated by Django 3.1 on 2020-08-08 12:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyac_api', '0005_auto_20200808_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 15, 35, 34, 546124)),
        ),
    ]
