# Generated by Django 3.1 on 2020-08-08 17:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyac_api', '0007_auto_20200808_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('application_date', models.DateTimeField(default=datetime.datetime(2020, 8, 8, 20, 50, 19, 518552))),
                ('applicant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='program',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 8, 20, 50, 19, 517552)),
        ),
        migrations.DeleteModel(
            name='Apllication',
        ),
        migrations.AddField(
            model_name='application',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='loyac_api.program'),
        ),
    ]
